name: abmbci
channels:
  - c4aarch64
  - conda-forge
  - defaults
variables:
  ABMSDK: /Users/kevindavis/Library/CloudStorage/Box-Box/Kevin\ Davis/Software/ABM/B-Alert\ Live\ v02.04.05.00/B-Alert\ Live\ v02.04.05.00/WinRoot/ABM/B-Alert/SDK
