[build-system]
requires = ["setuptools", "wheel", "pybind11", "scikit-build"]
build-backend = "setuptools.build_meta"

[project]
name = "abmbci"
version = "0.2.0"
dependencies = [
    "numpy",
    "pandas",
    "pyserial"
]
