[build-system]
requires = ["setuptools", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "abmbci"
version = "0.1.14"
dependencies = [
    "numpy",
    "pandas"
]

[tools.setuptools.packages.find]
exclude=["tests"]
