#ifndef INCLUDE_HEADSET_STATE_HPP_
#define INCLUDE_HEADSET_STATE_HPP_
enum State {
    DISCONNECTED,
    IDLE,
    INITIALIZED,
    IMPEDANCE,
    TECHNICAL,
    ACQUISITION
};
#endif  /* INCLUDE_HEADSET_STATE_HPP_ */